#!/usr/bin/env python
from slugify import slugify
from datetime import datetime, timedelta
import json
import random

objects = []
now = datetime.now()

# Poll are static so far
polls = {
    now: "Who likes the demo?",
    now-timedelta(days=1): "In the mood for Jorky?",
    now-timedelta(days=2): "How's DX doing?",
    now-timedelta(days=3): "Feeling good?",
    now-timedelta(days=4): "Like a s*x machine.",
}
poll_count = 0
for date, content in polls.iteritems():
    poll_count = poll_count + 1
    objects.append({
      "pk": poll_count,
      "model": "niko.poll",
      "fields": {
        "pub_date": str(date),
        "name": content,
        "slug": slugify( content )
      }
    })

# Generating votes... I know, it sounds so illegal :s
for i in range(1, 1000):
    objects.append( {
      "pk": i,
      "model": "niko.vote",
      "fields": {
        "ip": "127.0.0."+str( random.randint(2, 254) ),
        "poll": random.randint(1, poll_count),
        "pub_date": str(now - timedelta(days=random.randint(1, 10))),
        "mood": random.choice([0, 1, 2])
      }
    })

print json.dumps(objects)
